Stylised edges between different domains
Mazars-Tech/AD_Miner pull request #142
Opened 2024-06-04 11:45 UTC by Tanguy-Boisset

Small style tweak to make edges that link two nodes from different domains more visible.

2024-06-04 11:47 UTC, Tanguy-Boisset commented
I branched from main, if that's a problem, let me know

2024-06-04 11:52 UTC, Tanguy-Boisset commented
Only graph.js needs review

2024-06-04 16:21 UTC, snowpeacock requested changes
Problem with computers + to squash and merge with conventionnal commit name to trigger release :)

2024-06-04 16:50 UTC, snowpeacock approved these changes

2024-06-04 16:50 UTC, snowpeacock approved these changes

2024-06-05 22:39 UTC, jmbesnard approved these changes

2024-06-05 22:50 UTC, merged