fix: bugs with empty neo4j database
Mazars-Tech/AD_Miner pull request #56
Opened 2023-10-25 09:25 UTC by thomas-girard

![image](https://github.com/Mazars-Tech/AD_Miner/assets/70712826/18eeb4fe-8e5f-4862-9e13-02177b36dcb3)

2023-10-25 15:47 UTC, thomas-girard commented
![image](https://github.com/Mazars-Tech/AD_Miner/assets/70712826/74458924-dee4-43aa-adcd-8b824676fd4a)

2023-10-25 15:59 UTC, Tanguy-Boisset requested changes

2023-10-25 16:02 UTC, thomas-girard commented on ad_miner/__main__.py
> +        logger.print_error("Empty neo4j database : you need to fill it with Sharphound (https://github.com/BloodHoundAD/SharpHound), or BloodHound.py (https://github.com/dirkjanm/BloodHound.py) or Ru
![image](https://github.com/Mazars-Tech/AD_Miner/assets/70712826/e9298d7d-45e5-49e5-8641-18f724ec02ed)

2023-10-25 16:03 UTC, Tanguy-Boisset commented on ad_miner/__main__.py
> +        logger.print_error("Empty neo4j database : you need to fill it with Sharphound (https://github.com/BloodHoundAD/SharpHound), or BloodHound.py (https://github.com/dirkjanm/BloodHound.py) or Ru
All good !

2023-10-25 18:48 UTC, jmbesnard approved these changes

2023-10-26 07:33 UTC, clemtc approved these changes

2023-10-26 09:25 UTC, jmbesnard approved these changes

2023-10-26 10:48 UTC, Tanguy-Boisset approved these changes

2023-10-26 10:48 UTC, merged